name: information_schema_diff

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    env:
      PGHOST: ${{ secrets.PGHOST }}
      PGPORT: ${{ secrets.PGPORT }}
      PGUSER: ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dump information_schema
        run: |
          mkdir -p info_schema_snapshots
          timestamp=$(date -u +"%Y%m%dT%H%M%SZ")
          file="info_schema_snapshots/${timestamp}.json"
          psql "sslmode=require" -t -A -F, -c "
          SELECT json_build_object(
            'table_name', c.table_name,
            'column_name', c.column_name,
            'data_type', c.data_type,
            'is_nullable', c.is_nullable,
            'column_default', c.column_default,
            'ordinal_position', c.ordinal_position
          )
          FROM information_schema.columns c
          ORDER BY c.table_schema, c.table_name, c.ordinal_position;
          " | jq -s '.' > "$file"
          echo "Snapshot written to $file"
